name: lanars_test_task
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  provider: ^6.1.2
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.3
  flutter_bloc: ^8.1.6
  intl: ^0.18.1
  flutter_screenutil: ^5.9.3
  auto_route: ^5.0.1
  fpdart: ^1.1.0
  freezed_annotation: ^2.2.0
  freezed: ^2.1.0+1
  dio: ^4.0.4
  pretty_dio_logger: ^1.1.1
  http: ^0.13.6
  flutter_secure_storage: ^8.0.0
  hive_flutter: ^1.1.0
  uuid: ^3.0.7
  retrofit: ^3.3.1
  connectivity_plus: ^1.0.4
  dartx: ^1.1.0

  flutter_localizations:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator:
    git:
      url: https://github.com/yura2000/hive.git
      path: hive_generator
  flutter_gen_runner: ^5.3.2
  build_runner: ^2.4.9
  auto_route_generator: ^5.0.2
  flutter_lints: ^2.0.0
  json_serializable: ^6.1.4
  retrofit_generator: ^4.2.0


flutter:
  uses-material-design: true

  assets:
    - assets/gif/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto/Roboto-Italic.ttf
          style: italic
    - family: Bona Nova SC
      fonts:
        - asset: fonts/BonaNovaSC/BonaNovaSC-Regular.ttf
          weight: 400
        - asset: fonts/BonaNovaSC/BonaNovaSC-Bold.ttf
          weight: 700
        - asset: fonts/BonaNovaSC/BonaNovaSC-Italic.ttf
          style: italic

flutter_intl:
  enabled: true

