name: lanars_test_task
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  provider: ^6.1.2
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.3
  flutter_bloc: ^8.1.6
  intl: ^0.19.0
  flutter_screenutil: ^5.9.3
  auto_route: ^9.0.0
  injectable: ^2.1.2
  get_it: ^7.6.0
  fpdart: ^1.1.0
  freezed_annotation: ^2.2.0
  freezed: ^2.1.0+1
  dio: ^5.7.0
  pretty_dio_logger: ^1.1.1
  http: ^1.2.2
  flutter_secure_storage: ^9.2.2
  hive_flutter: ^1.1.0
  uuid: ^4.5.0
  retrofit: ^4.4.1
  connectivity_plus: ^6.0.5
  dartx: ^1.1.0
  photo_view: ^0.15.0
  cached_network_image: ^3.2.1
  pull_to_refresh_flutter3: ^2.0.2
  flutter_spinkit: ^5.2.0



  flutter_localizations:
    sdk: flutter
  realm: ^20.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  flutter_gen_runner: ^5.3.2
  build_runner: ^2.4.9
  auto_route_generator: ^9.0.0
  flutter_lints: ^4.0.0
  injectable_generator: ^2.1.6
  json_serializable: ^6.1.4
  retrofit_generator: ^8.2.1
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  image_path: "assets/icon/icon.jpg"
  adaptive_icon_foreground: "assets/icon/icon_foreground.png"
  android: true
  ios: true
  image_path_ios: "assets/icon/icon.jpg"
  adaptive_icon_background: "#213445"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/gif/
    - assets/images/
    - assets/icon/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto/Roboto-Italic.ttf
          style: italic
    - family: Bona Nova SC
      fonts:
        - asset: fonts/BonaNovaSC/BonaNovaSC-Regular.ttf
          weight: 400
        - asset: fonts/BonaNovaSC/BonaNovaSC-Bold.ttf
          weight: 700
        - asset: fonts/BonaNovaSC/BonaNovaSC-Italic.ttf
          style: italic

flutter_intl:
  enabled: true

